-- 项目数库
DROP DATABASE IF EXISTS `work_open_api`;
CREATE DATABASE `work_open_api` CHARACTER SET `utf8mb4` COLLATE = `utf8mb4_unicode_ci`;
USE `work_open_api`;

-- 项目用户
DROP USER IF EXISTS 'woa'@'%';
CREATE USER 'woa'@'%' IDENTIFIED BY 'Qwe54188_';
GRANT ALL PRIVILEGES ON `work_open_api`.* TO 'woa'@'%';
FLUSH PRIVILEGES;

-- 项目数表
CREATE TABLE IF NOT EXISTS `user`
(
    `id`            BIGINT AUTO_INCREMENT COMMENT 'id' PRIMARY KEY,
    `user_name`     VARCHAR(256)                           NULL COMMENT '用户昵称',
    `user_account`  VARCHAR(256)                           NOT NULL COMMENT '账号',
    `user_avatar`   VARCHAR(1024)                          NULL COMMENT '用户头像',
    `gender`        TINYINT                                NULL COMMENT '性别',
    `user_role`     VARCHAR(256) DEFAULT 'user'            NOT NULL COMMENT '用户角色: user / admin',
    `user_password` VARCHAR(512)                           NOT NULL COMMENT '密码',
    `access_key`    VARCHAR(512)                           NULL COMMENT 'accessKey',
    `secret_key`    VARCHAR(512)                           NULL COMMENT 'secretKey',
    `create_time`   DATETIME     DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    `update_time`   DATETIME     DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_delete`     TINYINT      DEFAULT 0                 NOT NULL COMMENT '是否删除',
    CONSTRAINT `uni_user_account`
        UNIQUE (`user_account`)
) COMMENT '用户表';

CREATE TABLE IF NOT EXISTS `interface_info`
(
    `id`              BIGINT                             NOT NULL AUTO_INCREMENT COMMENT '唯一标识' PRIMARY KEY,
    `name`            VARCHAR(256)                       NOT NULL COMMENT '接口名称',
    `description`     VARCHAR(256)                       NOT NULL COMMENT '接口描述',
    `url`             VARCHAR(256)                       NOT NULL COMMENT '接口地址',
    `request_params`  VARCHAR(256)                       NULL COMMENT '调用参数',
    `request_header`  TEXT                               NOT NULL COMMENT '接口请求头',
    `response_header` TEXT                               NOT NULL COMMENT '接口响应头',
    `status`          TINYINT                            NOT NULL COMMENT '接口状态(0-关闭, 1-开启)',
    `method`          VARCHAR(256)                       NOT NULL COMMENT '请求类型',
    `user_id`         BIGINT                             NOT NULL COMMENT '用户唯一标识',
    `create_time`     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    `update_time`     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted`      TINYINT  DEFAULT 0                 NOT NULL COMMENT '是否删除(0-未删, 1-已删)'
) COMMENT '接口信息表';

CREATE TABLE IF NOT EXISTS `user_interface_info`
(
    `id`                BIGINT                             NOT NULL AUTO_INCREMENT COMMENT '主键' PRIMARY KEY,
    `user_id`           BIGINT                             NOT NULL COMMENT '调用用户 id',
    `interface_info_id` BIGINT                             NOT NULL COMMENT '接口 id',
    `total_num`         INT      DEFAULT 0                 NOT NULL COMMENT '总调用次数',
    `left_num`          INT      DEFAULT 0                 NOT NULL COMMENT '剩余调用次数',
    `status`            INT      DEFAULT 0                 NOT NULL COMMENT '0-正常，1-禁用',
    `create_time`       DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    `update_time`       DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_delete`         TINYINT  DEFAULT 0                 NOT NULL COMMENT '是否删除(0-未删, 1-已删)'
) COMMENT '用户调用接口关联表';

-- 项目测试
INSERT INTO `user` (`user_name`,
                    `user_account`,
                    `user_avatar`,
                    `gender`,
                    `user_role`,
                    `user_password`,
                    `access_key`,
                    `secret_key`)
VALUES ('limou',
        'limou',
        'https://avatars.githubusercontent.com/u/113878415?s=400&u=9f10b63e033c9504615bc475581441478424e04b&v=4',
        1,
        'admin',
        'bde672b1737093d5f9ad55ccc26f32eb',
        'limou3434',
        'abcdefgh'),
       ('dimou',
        'dimou',
        'https://picx.zhimg.com/v2-e3034a40544d588e4f630b3ec7210030_xll.jpg?source=32738c0c&needBackground=1',
        1,
        'user',
        'bde672b1737093d5f9ad55ccc26f32eb',
        'dimou3434',
        'abcdefgh');

INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('刘笑愚',
        '吴琪',
        'www.wesley-trantow.com',
        '万鸿煊',
        '王越彬',
        0,
        '黄雪松',
        26826);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('潘展鹏',
        '叶晓啸',
        'www.courtney-kassulke.net',
        '戴鸿煊',
        '袁荣轩',
        0,
        '谢立诚',
        434);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('覃天宇',
        '冯昊强',
        'www.johnie-harris.name',
        '武博文',
        '戴思聪',
        0,
        '毛昊焱',
        2334);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('谭黎昕',
        '傅哲瀚',
        'www.josette-adams.org',
        '覃振家',
        '吕风华',
        0,
        '孔鹭洋',
        57553);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('魏嘉熙',
        '沈思聪',
        'www.wyatt-nader.org',
        '韩嘉懿',
        '熊思源',
        0,
        '姚立轩',
        0);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('龚修洁',
        '宋锦程',
        'www.jerlene-grimes.io',
        '廖哲瀚',
        '张建辉',
        0,
        '林天宇',
        34618);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('蒋鑫磊',
        '谭明辉',
        'www.micki-dicki.name',
        '唐雪松',
        '沈鹏飞',
        0,
        '罗烨华',
        27);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('钱雪松',
        '吕鹏',
        'www.andy-russel.org',
        '范烨伟',
        '邵黎昕',
        0,
        '苏笑愚',
        5460331959);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('严晟睿',
        '唐晟睿',
        'www.nadine-bradtke.name',
        '郑峻熙',
        '冯琪',
        0,
        '秦烨华',
        90477376);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('段浩轩',
        '潘文博',
        'www.terrence-konopelski.co',
        '韩雨泽',
        '袁志强',
        0,
        '陈博文',
        9453614492);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('黎健雄',
        '龙泽洋',
        'www.rodney-douglas.io',
        '冯晟睿',
        '韩明哲',
        0,
        '蒋弘文',
        70703);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('邵绍齐',
        '范振家',
        'www.wilbur-reinger.name',
        '邹绍辉',
        '叶哲瀚',
        0,
        '姚子轩',
        24180);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('顾博文',
        '张瑾瑜',
        'www.kittie-kautzer.name',
        '龙修杰',
        '万弘文',
        0,
        '潘弘文',
        334268466);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('唐明辉',
        '郝耀杰',
        'www.ed-barton.org',
        '蒋晓啸',
        '段钰轩',
        0,
        '程明',
        6);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('陶泽洋',
        '龙语堂',
        'www.shane-braun.io',
        '杜驰',
        '徐笑愚',
        0,
        '熊展鹏',
        8);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('孔炎彬',
        '龚昊天',
        'www.rolf-wiegand.net',
        '赵明辉',
        '覃昊天',
        0,
        '白天宇',
        7453201);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('陈梓晨',
        '高志泽',
        'www.norah-goldner.org',
        '何鹤轩',
        '郝鹏',
        0,
        '李煜城',
        791);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('白思',
        '汪懿轩',
        'www.hugo-bradtke.co',
        '于立轩',
        '毛楷瑞',
        0,
        '罗俊驰',
        3219);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('李琪',
        '谭健雄',
        'www.gerry-dicki.biz',
        '龙果',
        '吴晟睿',
        0,
        '马昊焱',
        61151986);
INSERT INTO `interface_info` (`name`,
                              `description`,
                              `url`,
                              `request_header`,
                              `response_header`,
                              `status`,
                              `method`,
                              `user_id`)
VALUES ('吴思',
        '吴志泽',
        'www.kareem-feest.io',
        '汪黎昕',
        '赵瑾瑜',
        0,
        '邱致远',
        6);