// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/home/ljp/git/edtechhub/work-open-api/client/work-open-api-react/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/home/ljp/git/edtechhub/work-open-api/client/work-open-api-react/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/home/ljp/git/edtechhub/work-open-api/client/work-open-api-react/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
